- type: job
  id: BKBPLAMED
  name: job-name-silicon-BPLAMED
  description: job-description-silicon-BPLAMED
  playTimeTracker: BPLAMED
  joinNotifyCrew: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24000
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 14400
  icon: JobIconUnknown
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: BackmenDroneMED
  startingGear: RobotGear # for char preview only
